/*
 * Copyright (c) 2021 NetEase, Inc.  All rights reserved.
 * Use of this source code is governed by a MIT license that can be found in the LICENSE file.
 */

package com.netease.yunxin.app.wisdom.edu.logic

import com.netease.lava.nertc.sdk.NERtcConstants

/**
 * Created by hzsunyj on 2021/8/27.
 */
enum class NEEduRtcCode(val code: Int, val msg: String) {
    //rtc error
    ENGINE_ERROR_FATAL(NERtcConstants.ErrorCode.ENGINE_ERROR_FATAL, ""),
    ENGINE_ERROR_OUT_OF_MEMORY(NERtcConstants.ErrorCode.ENGINE_ERROR_OUT_OF_MEMORY, ""),
    ENGINE_ERROR_INVALID_PARAM(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_PARAM, ""),
    ENGINE_ERROR_NOT_SUPPORTED(NERtcConstants.ErrorCode.ENGINE_ERROR_NOT_SUPPORTED, ""),
    ENGINE_ERROR_INVALID_STATE(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_STATE, ""),
    ENGINE_ERROR_LACK_OF_RESOURCE(NERtcConstants.ErrorCode.ENGINE_ERROR_LACK_OF_RESOURCE, ""),
    ENGINE_ERROR_INVALID_INDEX(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_INDEX, ""),
    ENGINE_ERROR_DEVICE_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_DEVICE_NOT_FOUND, ""),
    ENGINE_ERROR_INVALID_DEVICE_SOURCEID(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_DEVICE_SOURCEID, ""),
    ENGINE_ERROR_INVALID_VIDEO_PROFILE(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_VIDEO_PROFILE, ""),
    ENGINE_ERROR_CREATE_DEVICE_SOURCE_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_CREATE_DEVICE_SOURCE_FAIL, ""),
    ENGINE_ERROR_INVALID_RENDER(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_RENDER, ""),
    ENGINE_ERROR_DEVICE_PREVIEW_ALREADY_STARTED(NERtcConstants.ErrorCode.ENGINE_ERROR_DEVICE_PREVIEW_ALREADY_STARTED, ""),
    ENGINE_ERROR_TRANSMIT_PENDDING(NERtcConstants.ErrorCode.ENGINE_ERROR_TRANSMIT_PENDDING, ""),
    ENGINE_ERROR_CONNECT_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_CONNECT_FAIL, ""),
    ENGINE_ERROR_CREATE_DUMP_FILE_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_CREATE_DUMP_FILE_FAIL, ""),
    ENGINE_ERROR_START_DUMP_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_START_DUMP_FAIL, ""),
    ENGINE_ERROR_ROOM_ALREADY_JOINED(NERtcConstants.ErrorCode.ENGINE_ERROR_ROOM_ALREADY_JOINED, ""),
    ENGINE_ERROR_ROOM_NOT_JOINED(NERtcConstants.ErrorCode.ENGINE_ERROR_ROOM_NOT_JOINED, ""),
    ENGINE_ERROR_ROOM_REPLEATEDLY_LEAVE(NERtcConstants.ErrorCode.ENGINE_ERROR_ROOM_REPLEATEDLY_LEAVE, ""),
    ENGINE_ERROR_REQUEST_JOIN_ROOM_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_REQUEST_JOIN_ROOM_FAIL, ""),
    ENGINE_ERROR_SESSION_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_SESSION_NOT_FOUND, ""),
    ENGINE_ERROR_USER_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_USER_NOT_FOUND, ""),
    ENGINE_ERROR_INVALID_USERID(NERtcConstants.ErrorCode.ENGINE_ERROR_INVALID_USERID, ""),
    ENGINE_ERROR_MEDIA_NOT_STARTED(NERtcConstants.ErrorCode.ENGINE_ERROR_MEDIA_NOT_STARTED, ""),
    ENGINE_ERROR_SOURCE_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_SOURCE_NOT_FOUND, ""),
    ENGINE_ERROR_CONNECTION_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_CONNECTION_NOT_FOUND, ""),
    ENGINE_ERROR_STREAM_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_STREAM_NOT_FOUND, ""),
    ENGINE_ERROR_ADD_TRACK_FAIL(NERtcConstants.ErrorCode.ENGINE_ERROR_ADD_TRACK_FAIL, ""),
    ENGINE_ERROR_TRACK_NOT_FOUND(NERtcConstants.ErrorCode.ENGINE_ERROR_TRACK_NOT_FOUND, ""),
    ENGINE_ERROR_MEDIA_CONNECTION_DISCONNECTED(NERtcConstants.ErrorCode.ENGINE_ERROR_MEDIA_CONNECTION_DISCONNECTED, ""),
    ENGINE_ERROR_SIGNAL_DISCONNECTED(NERtcConstants.ErrorCode.ENGINE_ERROR_SIGNAL_DISCONNECTED, ""),
    ENGINE_ERROR_SERVER_KICKED(NERtcConstants.ErrorCode.ENGINE_ERROR_SERVER_KICKED, ""),
    ENGINE_ERROR_ROOM_CLOSED(NERtcConstants.ErrorCode.ENGINE_ERROR_ROOM_CLOSED, ""),
}